import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const browser=await chromium.launch({channel:'msedge',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000},colorScheme:'light',reducedMotion:'reduce'});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:5173/');
await page.locator('.channel').last().waitFor();
assert.equal(await page.locator('.channel').count(),14);
await page.getByRole('button',{name:'Space',exact:true}).click();
assert.equal(await page.locator('.channel').count(),3);
await page.getByRole('searchbox').fill('nothing matches this');
assert.equal(await page.locator('.channel').count(),0);
await page.getByRole('button',{name:'Show all channels'}).click();
await page.getByRole('searchbox').fill('Veritasium');
assert.equal(await page.locator('.channel').count(),1);
await page.getByRole('button',{name:'Explore channel: Veritasium',exact:true}).click();
await page.getByRole('dialog').waitFor();
assert.match(await page.getByRole('dialog').innerText(),/Who is it for/);
await page.keyboard.press('Escape');
assert.equal(await page.getByRole('dialog').isVisible(),false);
assert.equal(await page.getByRole('button',{name:'Explore channel: Veritasium',exact:true}).evaluate(e=>e===document.activeElement),true);
await page.getByRole('searchbox').fill('');
await page.getByRole('button',{name:'Surprise me'}).click();
assert.equal(await page.getByRole('dialog').isVisible(),true);
await page.getByRole('button',{name:'Close channel details'}).click();
await page.locator('.video').first().waitFor();
assert.equal(await page.locator('.video').count(),6);
await page.getByRole('button',{name:'Show more uploads'}).click();
assert.equal(await page.locator('.video').count(),12);
await fs.mkdir('docs/qa',{recursive:true});
await page.evaluate(()=>scrollTo(0,0));
await page.screenshot({path:'docs/qa/desktop.png',fullPage:true});
await page.getByRole('button',{name:'Use dark theme'}).click();
assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');
await page.screenshot({path:'docs/qa/dark.png',fullPage:true});
await page.getByRole('button',{name:'Use light theme'}).click();
for(const width of [375,768,1024,1440]){
 await page.setViewportSize({width,height:900});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,`overflow at ${width}`);
}
await page.setViewportSize({width:375,height:812});
await page.evaluate(()=>scrollTo(0,0));
await page.screenshot({path:'docs/qa/mobile.png',fullPage:true});
await page.route('**/data/uploads.json',route=>route.abort());
await page.reload();
await page.getByRole('heading',{name:/latest uploads couldn/}).waitFor();
await page.unroute('**/data/uploads.json');
await page.getByRole('button',{name:'Try again'}).click();
await page.locator('.video').first().waitFor();
assert.deepEqual(errors,[]);
console.log('PASS: search, filters, empty state, dialog and focus, surprise, pagination, themes, 4 viewports, feed error/retry; no JS errors.');
await browser.close();
